### ISSUE TITLE
应该说是 Markdown 的渲染问题？

### ISSUE THREAD

**Issue by parasomn1a** [LIlGG/halo-comment-sakura#17]
在评论框中输入文本

```
url: 
```

会被解析成这个样子：
![image](https://user-images.githubusercontent.com/22992947/112251426-2e051480-8c96-11eb-87b3-6342778f8375.png)

因为使用主题 `Anatole` 时没有这个问题，所以我认为应该是主题的问题
![image](https://user-images.githubusercontent.com/22992947/112251643-9fdd5e00-8c96-11eb-880b-7153193b0795.png)

**Comment by parasomn1a** [comment]
和 Tieba 的 emoji 解析有关
通过测试发现当出现 `:文本:` 时就会出现这样的问题，贴吧的 emoji 解析也是 `:文本:`

或许移除贴吧的 emoji 可破

**Comment by LIlGG** [comment]
> 和 Tieba 的 emoji 解析有关
> 通过测试发现当出现 `:文本:` 时就会出现这样的问题，贴吧的 emoji 解析也是 `:文本:`（BBcode）
> 
> 或许移除贴吧的 emoji 可破（或者更换 Tieba 的 emoji 解析）

辛苦了，目前来说或许更改 emoji 的解析防止冲突是最好的做法。

**Comment by parasomn1a** [comment]
应该是这里：

https://github.com/LIlGG/halo-comment-sakura/blob/6c86198006f5744c4859cdd46f3e10bcd5c4c10d/src/components/CommentEditor.vue#L381

**Comment by LIlGG** [comment]
> PS：我对 npm、vue 一窍不通呢…… 本想尝试修改后提交 PR 的，无奈 build 不通过
> 希望能有个清晰 PR 指引（我是按照 [halo-comment](https://github.com/halo-dev/halo-comment) 操作的）

抱歉嗷，那段时间有点忙，刚刚新增了 PR 指南，你可以看一看。
