### ISSUE TITLE
在评论框里同时输入 markdown 和表情会报错

### ISSUE THREAD

**Issue by qinhua** [LIlGG/halo-comment-sakura#37]
首先，很感谢大佬提供这么好用的评论组件 ❤️

是这样，今天在使用时候发现了一个异常，如下：
在评论框中输入 `## 我是标题 :aini: `  ，然后点击预览或者提交会没任何反应，控制台有红色的字样，如下：

```text
lib.js:38 TypeError: t.codeEmoji is not a function
Please report this to https://github.com/markedjs/marked.
    at e.t.parseInline (halo-comment.min.js:16)
    at e.t.parse (halo-comment.min.js:16)
    at Function.e.parse (halo-comment.min.js:16)
    at fe (halo-comment.min.js:16)
    at a.renderedContent (halo-comment.min.js:16)
    at fn.get (lib.js:38)
    at fn.evaluate (lib.js:38)
    at a.renderedContent (lib.js:38)
    at a.r (halo-comment.min.js:16)
    at a.e._render (lib.js:38)
```
发现只要在 `markdown` 相关符号同一行用标签都会导致解析错误，请问大佬这个可以做下异常处理吗？

**Comment by LIlGG** [comment]
了解了~ 非常感谢提出的问题，不过现在正在上班。 晚上回去我会定位一下问题然后解决一下。

**Comment by LIlGG** [comment]
也很欢迎提交相应的 pr

**Comment by qinhua** [comment]
@LIlGG 俺刚看了下，还涉及到 `l-marked` 这个包，好像也是大佬自己修改的版本吧，最后发现其中有个 `parseInline` 方法中直接加下三目判断下就不会报错了，`bilibiliEmoji` 和 `codeEmoji`  都要判断一下。

看来要先改下  `l-marked` 这个包，然后重新构建一次 `halo-comment`。刚好我也在折腾这个，提个 pr 吧，😆

```js
// src/Parser.js 中的   parseInline 方法
case 'bilibiliEmoji': {
    out += renderer.bilibiliEmoji ? renderer.bilibiliEmoji(token.text) : token.text;
    break;
}
case 'textEmoji': {
    out += renderer.textEmoji(token.text);
    break;
}
case 'codeEmoji': {
    out += renderer.codeEmoji ? renderer.codeEmoji(token.text) : token.text;
    break;
}
```

**Comment by qinhua** [comment]
@LIlGG 已经给 `l-marked` 提了 `pr` 🙆‍♂️

**Comment by LIlGG** [comment]
> @LIlGG 已经给 `l-marked` 提了 `pr` 🙆‍♂️

@qinhua  了解了，非常感谢提交的 PR。本来想今天 review 的，但抽不开时间来。所以最大可能是在明天甚至周六之后来处理这个 PR。希望能够理解！

**Comment by LIlGG** [comment]
或者我这边可以在上班时间登录 github ，如果您有意向的话，希望可以能够和我共同维护这个仓库！

**Comment by qinhua** [comment]
@LIlGG 希望可以加入共同维护

**Comment by LIlGG** [comment]
> @LIlGG 希望可以加入共同维护

非常感谢！近段时间实在是太忙了，抽不开空来处理这些东西。有你一起帮助维护实在是帮了大忙！！我已经拉你进了 comment 和 其他相关的仓库

**Comment by qinhua** [comment]
感谢大佬

**Comment by qinhua** [comment]
@LIlGG 需要大佬帮忙把 `marked` 那个项目发个新的 npm 版本。

**Comment by LIlGG** [comment]
> @LIlGG 需要大佬帮忙把 `marked` 那个项目发个新的 npm 版本。

了解了。现在发布

**Comment by LIlGG** [comment]
> @LIlGG 需要大佬帮忙把 `marked` 那个项目发个新的 npm 版本。

已经发布 1.1.1 版本。

**Comment by qinhua** [comment]
ok
