### ISSUE TITLE
v1.3.0版本页面第一条评论提交后控制台报错，后面第二条开始都是正常的

### ISSUE THREAD

**Issue by Sanarous** [LIlGG/halo-comment-sakura#4]
使用版本：v1.3.0
使用主题：HanShan主题，应该不是兼容性问题
问题描述：在任意一个零评论的页面，使用 1.3.0 版本提交第一条评论后，控制台会报如下错误，页面评论处无自动新增，但是后台看到已经评论成功，且继续评论的第二条、第三条等都是正常自动新增的，只有第一条有问题，希望能够尽快解决
![image](https://user-images.githubusercontent.com/42607376/86589914-1fb88080-bfc1-11ea-8228-90d479aeb2f5.png)

**Comment by LIlGG** [comment]
应该是自动新增功能找不到节点而产生的BUG 我会尽快解决
