### ISSUE TITLE
层次过多的BUG

### ISSUE THREAD

**Issue by LIlGG** [LIlGG/halo-comment-sakura#5]
目前允许层次为无限层，应该修改为最大6层，或者由用户指定

**Comment by ruibaby** [comment]
说得好，那么怎么实现呢？

**Comment by LIlGG** [comment]
> 说得好，那么怎么实现呢？

蕾姆！！竟然还活着。。其实不难的。设置css第多少层以后的样式就行了。这两天已经在开始改动评论组件了
