### ISSUE TITLE
评论插件第一次无法正确展示

### ISSUE THREAD

**Issue by robinch-top** [LIlGG/halo-comment-sakura#7]
我使用了[halo-theme-siren](https://github.com/halo-dev/halo-theme-siren)主题，然后使用这个评论组件，第一次进入网站时，点击查看评论，并不能展现评论组件，只能刷新一下网站，再点击才能展现，这是什么问题呢？
![UTOOLS1595482810809.png](https://img04.sogoucdn.com/app/a/100520146/aa293612ad40674c5f776639d928755a)

**Comment by LIlGG** [comment]
> 我使用了[halo-theme-siren](https://github.com/halo-dev/halo-theme-siren)主题，然后使用这个评论组件，第一次进入网站时，点击查看评论，并不能展现评论组件，只能刷新一下网站，再点击才能展现，这是什么问题呢？
> ![UTOOLS1595482810809.png](https://camo.githubusercontent.com/1f1af651ed476085cba6a02576a3ec940b77d41e/68747470733a2f2f696d6730342e736f676f7563646e2e636f6d2f6170702f612f3130303532303134362f6161323933363132616434303637346335663737363633396439323837353561)

这并不是评论组件的BUG，而是属于siren主题的BUG。 详见[halo-dev/halo-theme-siren#1](https://github.com/halo-dev/halo-theme-siren/issues/1)。 该问题由于pjax写法问题，不能加载代码样式造成。 
或许你可以考虑使用[sakura](https://github.com/LIlGG/halo-theme-sakura)主题。 该主题基于Siren主题制作，解决了Siren主题已知的所有BUG，在精简状态下同Siren主题

**Comment by robinch-top** [comment]
感谢的你的解答，我正在尝试使用[sakura](https://github.com/LIlGG/halo-theme-sakura)主题
