### ISSUE TITLE
自定义配置无效

### ISSUE THREAD

**Issue by parasomn1a** [LIlGG/halo-comment-sakura#9]
```js
	var configs = {
    		autoLoad: true,
    		showUserAgent: true,
		gravatarSource: "//sdn.geekzu.org/avatar",
		loadingStyle: "balls"
	}
```

使用[sakura](https://github.com/LIlGG/halo-theme-sakura)主题，在[这里](https://github.com/LIlGG/halo-theme-sakura/blob/d4582622070366822bca68e8fee8b8924e23169f/comments.ftl#L6)做的修改

但头像获取仍为从 `v2ex` 获取

**Comment by LIlGG** [comment]
嗯，这块确实有配置问题，近期会对评论组件进行新的改动，这地方也会完善
